Cloud testapp
Otus-DevOps-2018-02/bulnv_infra pull request #5
Opened 2018-03-25 06:00 UTC by bulnv

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Написан install_ruby.sh
 - Написан install_mongodb.sh
 - Написан deploy.sh
 - Написан startup_script.sh
 - В README.md добавлено описание использованных команд gcloud

## Как запустить проект:
 - Используя команды из README.md и s tartup script создать VM в GCP 

## Как проверить работоспособность:
 - зайти на testapp_IP:testapp_port

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-03-29 05:40 UTC, sedovandrew submitted a review, later dismissed
Николай, привет!

1. Твой startup_script не отрабатывает, не ставится база данных Mongo. Поправь.
2. Правило файрвола создаётся, но данное правило не позволяет получить доступ к приложению Reddit. Посмотри, что в нём не так.

2018-03-31 09:24 UTC, bulnv commented
- Правила фаервола поправил
 - Со startup_script проблемы не выявил. На всякий случай по удалял там лишние пробелы.
Прошу еще раз проверить.
http://prntscr.com/iyuuyy

2018-04-01 19:56 UTC, Nklya requested changes
Добрый вечер.

Николай, как Андрей и писал, стартап скрипт у тебя не рабочий.

Подсказка ниже.


P.S. ДЗ принимаются по очереди, поэтому этот PR блокирует остальные.

2018-04-01 19:56 UTC, Nklya commented on startup_script.sh
> +/etc/apt/sources.list.d/mongodb-org-3.2.list'
Ошибка здесь если что.

2018-04-01 19:59 UTC, Nklya commented
И результат 
<img width="961" alt="screen shot 2018-04-01 at 22 59 23" src="https://user-images.githubusercontent.com/26086394/38176917-58cb16f0-3600-11e8-8186-d62092bf885a.png">

2018-04-07 08:22 UTC, Nklya approved these changes
Да, теперь все ок 👍

2018-04-10 15:00 UTC, Nklya commented
Проверенные PR нужно сливать в мастер (нажимать кнопку "Merge pull request")!

2018-04-14 05:24 UTC, merged