Terraform 2
Otus-DevOps-2018-02/bulnv_infra pull request #8
Opened 2018-04-08 07:37 UTC by bulnv

# Выполнено ДЗ № 8

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
  - Конфигурация поделена на три модуля (app\db\vpc)
  - А затем на окружения (stage\prod)
  - Восстановлена функциональность приложения 

## Как запустить проект:
 - запустить terraform apply в директории terraforn

## Как проверить работоспособность:
 - перейти по ссылке http://app_external_ip:9292

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-04-12 15:44 UTC, Nklya requested changes
Ревью этого ДЗ будет произведено после мержа предыдущих проверенных ДЗ в мастер.

2018-04-14 13:52 UTC, bulnv commented
Предыдущие ДЗ смерджены. Ожидаю ревью.

2018-04-16 08:47 UTC, Nklya approved these changes
Добрый день.

Николай, условия ДЗ выполнены, все выглядит ок 👍 

Комментарии ниже

2018-04-16 08:47 UTC, Nklya commented on terraform/app.tf.bkp
> +resource "google_compute_instance" "app" {
Можно было резервные копии выкинуть в `terraform/files`

2018-04-16 08:47 UTC, Nklya commented on terraform/variables.tf
> +}
Не думаю, что эта куча переемнных сейчас здесь нужна.

2018-04-16 08:47 UTC, Nklya commented on terraform/modules/db/outputs.tf
> +output "db_external_ip" {
Не похоже это на external_ip

2018-04-16 08:47 UTC, Nklya commented on terraform/modules/db/files/install_mongodb.sh
> +sudo sed -i 's/bindIp: 127.0.0.1/bindIp: 0.0.0.0/g' /etc/mongod.conf
Все что нужно было здесь сделать находится после 6 строчки.
Инстанс уже поднимается из образа с монгой.

2018-04-16 14:09 UTC, Nklya commented on terraform/backend.tf
> +terraform {
Ну и настройка remote state здесь имеет весьма мало смысла.
Основная инфра разворачивается из terraform/prod и stage

2018-04-16 16:26 UTC, merged